language: java

jdk:
  - openjdk11

install:
  - mvn test-compile -DskipTests -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./target/generated-docs"
  on:
    branch: eider-initialization