server:
  port: 9000
  servlet:
    context-path:

logging:
  file:
    name: logs/eider.log
  level:
    edu.tamu: INFO
    org.springframework: INFO

spring:

  devtools.restart.enabled: true

  h2.console.enabled: true

  sql:
    init:
      platform: h2
      # platform: postgres

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/eider

    username: spring
    password: spring

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQL10Dialect

    show-sql: true
    hibernate.ddl-auto: create-drop

app:
  username: admin
  password: admin

  default-identifier-type-name: Unspecified

  security:
    allow-access: http://localhost,http://localhost:9000,http://127.0.0.1
